version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "eslint"
        versions: ["9.x"]
      - dependency-name: "chai"
        versions: ["5.x"]
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
